---
title: "IRT"
author: "Mar??a Jos?? Beltr??n"
date: "5/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## IRT

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(lubridate)
library(plyr)
library(cluster)
library(MASS)
library(readxl)
library(gridExtra)
```


Importamos los datos. Nos quedamos unicamente con las respuestas a las 33 preguntas de cada alumno (4to curso UIB y Valencia)

```{r}
datosValencia_T1 <- read_excel("/Users/MariaJose/Desktop/TFG/Encuesta/PID_E_II_control3_T1T2T3_4codificado-1.xlsx", sheet = "control3_T1", range = cell_cols("AN:BT")) %>%
  dplyr::rename(Pregunta_1 = "1. Me resulta facil darme cuenta de las intenciones de las personas que me rodean",
                Pregunta_2 = "2. Me siento bien si los demas se divierten (lo pasan bien)",
                Pregunta_3 = "3. No me pongo triste solo porque un amigo lo este",
                Pregunta_4 = "4. Si un amigo consigue un trabajo muy deseado, me entusiasmo con el",
                Pregunta_5 = "5. Me afecta demasiado ver programas de television donde se muestran los problemas de otras personas",
                Pregunta_6 = "6. Antes de tomar una decision, intento tener en cuenta todos los puntos de vista",
                Pregunta_7 = "7. Rara vez reconozco como se siente una persona con solo mirarla",
                Pregunta_8 = "8. Me afecta poco escuchar desgracias sobre personas desconocidas",
                Pregunta_9 = "9. Me hace ilusion  ver que un amigo nuevo se encuentra a gusto en nuestro grupo",
                Pregunta_10 = "10. Me es dificil entender como se siente una persona ante una situacion que no he vivido",
                Pregunta_11 = "11. Cuando un amigo se ha portado mal conmigo, intento entender los motivos por los que lo ha hecho",
                Pregunta_12 = "12. A menos que se trate de algo muy grave, me cuesta llorar con lo que les sucede a otros",
                Pregunta_13 = "13. Reconozco facilmente cuando alguien esta de mal humor",
                Pregunta_14 = "14. No siempre me doy cuenta cuando la persona que tengo al lado se siente mal",
                Pregunta_15 = "15. Intento ponerme en el lugar de los demas para saber como actuaran",
                Pregunta_16 = "16. Cuando a alguien le sucede algo bueno, siento alegria",
                Pregunta_17 = "17. Si tengo una opinion formada no presto mucha atencion a los argumentos de los demas",
                Pregunta_18 = "18. A veces sufro mas con las desgracias de los demas que ellos mismos",
                Pregunta_19 = "19. Me siento feliz solo con ver felices a otras personas",
                Pregunta_20 = "20. Cuando alguien tiene un problema, intento imaginarme como me sentiria si estuviera en su lugar",
                Pregunta_21 = "21. No siento especial alegria si alguien me cuenta que ha tenido un golpe de suerte",
                Pregunta_22 = "22. Cuando veo que alguien  recibe un regalo no puedo reprimir una sonrisa",
                Pregunta_23 = "23. No puedo evitar llorar con los testimonios de personas desconocidas",
                Pregunta_24 = "24. Cuando conozco gente nueva me doy cuenta de la impresion que se han llevado de mi",
                Pregunta_25 = "25. Cuando mis amigos me cuentan que les va bien, no le doy mucha importancia",
                Pregunta_26 = "26. Encuentro dificil ver las cosas desde el punto de vista de otras personas",
                Pregunta_27 = "27. Entender como se siente otra persona es algo muy facil para mi",
                Pregunta_28 = "28. No soy de esas personas que se deprimen con los problemas de los demas",
                Pregunta_29 = "29. Intento comprender mejor a mis amigos mirando las situaciones desde su perspectiva",
                Pregunta_30 = "30. Me considero una persona fria porque no me conmuevo facilmente",
                Pregunta_31 = "31. Me doy cuenta cuando las personas cercanas a mi estan especialmente contentas, aunque no me hayan contado el motivo",
                Pregunta_32 = "32. Me resulta dificil ponerme en el lugar de personas con las que no estoy de acuerdo",
                Pregunta_33 = "33. Me doy cuenta cuando alguien intenta esconder sus verdaderos sentimientos")
```

```{r}
datosUIB_T1 <- read_excel("/Users/MariaJose/Desktop/TFG/Encuesta/PID_E_II_int4_T1T2T3_prog_intensivo_4codificado.xlsx", sheet = "EII_int_T1", range = cell_cols("AN:BT")) %>%
  dplyr::rename(Pregunta_1 = '1TECA1', Pregunta_2 = '1TECA2', Pregunta_3 = '1TECA3',Pregunta_4 = '1TECA4', Pregunta_5 = '1TECA5', Pregunta_6 = '1TECA6', Pregunta_7 = '1TECA7', Pregunta_8 = '1TECA8', Pregunta_9 = '1TECA9', Pregunta_10 = '1TECA10', Pregunta_11 =  '1TECA11', Pregunta_12 = '1TECA12', Pregunta_13 = '1TECA13', Pregunta_14 = '1TECA14', Pregunta_15 = '1TECA15', Pregunta_16 = '1TECA16', Pregunta_17 = '1TECA17',Pregunta_18 = '1TECA18', Pregunta_19 = '1TECA19', Pregunta_20 = '1TECA20', Pregunta_21 = '1TECA21',Pregunta_22 = '1TECA22', Pregunta_23 = '1TECA23',Pregunta_24 = '1TECA24', Pregunta_25 = '1TECA25', Pregunta_26 = '1TECA26', Pregunta_27 = '1TECA27', Pregunta_28 = '1TECA28', Pregunta_29 = '1TECA29', Pregunta_30 = '1TECA30', Pregunta_31 = '1TECA31', Pregunta_32 = '1TECA32', Pregunta_33 = '1TECA33')
```

Juntamos los datos

```{r echo=TRUE, include=FALSE}
datos_T1 <- rbind(datosValencia_T1, datosUIB_T1)
```


Invertimos el orden de las respuestas para las preguntas necesarias

```{r echo=TRUE, include=FALSE}
datos_T1$Pregunta_3[datos_T1$Pregunta_3 == "1"] <- 6
datos_T1$Pregunta_3[datos_T1$Pregunta_3 == "2"] <- 7
datos_T1$Pregunta_3[datos_T1$Pregunta_3 == "4"] <- 8
datos_T1$Pregunta_3[datos_T1$Pregunta_3 == "5"] <- 9
datos_T1$Pregunta_3[datos_T1$Pregunta_3 == "6"] <- 5
datos_T1$Pregunta_3[datos_T1$Pregunta_3 == "7"] <- 4
datos_T1$Pregunta_3[datos_T1$Pregunta_3 == "8"] <- 2
datos_T1$Pregunta_3[datos_T1$Pregunta_3 == "9"] <- 1

datos_T1$Pregunta_7[datos_T1$Pregunta_7 == "1"] <- 6
datos_T1$Pregunta_7[datos_T1$Pregunta_7 == "2"] <- 7
datos_T1$Pregunta_7[datos_T1$Pregunta_7 == "4"] <- 8
datos_T1$Pregunta_7[datos_T1$Pregunta_7 == "5"] <- 9
datos_T1$Pregunta_7[datos_T1$Pregunta_7 == "6"] <- 5
datos_T1$Pregunta_7[datos_T1$Pregunta_7 == "7"] <- 4
datos_T1$Pregunta_7[datos_T1$Pregunta_7 == "8"] <- 2
datos_T1$Pregunta_7[datos_T1$Pregunta_7 == "9"] <- 1

datos_T1$Pregunta_8[datos_T1$Pregunta_8 == "1"] <- 6
datos_T1$Pregunta_8[datos_T1$Pregunta_8 == "2"] <- 7
datos_T1$Pregunta_8[datos_T1$Pregunta_8 == "4"] <- 8
datos_T1$Pregunta_8[datos_T1$Pregunta_8 == "5"] <- 9
datos_T1$Pregunta_8[datos_T1$Pregunta_8 == "6"] <- 5
datos_T1$Pregunta_8[datos_T1$Pregunta_8 == "7"] <- 4
datos_T1$Pregunta_8[datos_T1$Pregunta_8 == "8"] <- 2
datos_T1$Pregunta_8[datos_T1$Pregunta_8 == "9"] <- 1

datos_T1$Pregunta_10[datos_T1$Pregunta_10 == "1"] <- 6
datos_T1$Pregunta_10[datos_T1$Pregunta_10 == "2"] <- 7
datos_T1$Pregunta_10[datos_T1$Pregunta_10 == "4"] <- 8
datos_T1$Pregunta_10[datos_T1$Pregunta_10 == "5"] <- 9
datos_T1$Pregunta_10[datos_T1$Pregunta_10 == "6"] <- 5
datos_T1$Pregunta_10[datos_T1$Pregunta_10 == "7"] <- 4
datos_T1$Pregunta_10[datos_T1$Pregunta_10 == "8"] <- 2
datos_T1$Pregunta_10[datos_T1$Pregunta_10 == "9"] <- 1

datos_T1$Pregunta_12[datos_T1$Pregunta_12 == "1"] <- 6
datos_T1$Pregunta_12[datos_T1$Pregunta_12 == "2"] <- 7
datos_T1$Pregunta_12[datos_T1$Pregunta_12 == "4"] <- 8
datos_T1$Pregunta_12[datos_T1$Pregunta_12 == "5"] <- 9
datos_T1$Pregunta_12[datos_T1$Pregunta_12 == "6"] <- 5
datos_T1$Pregunta_12[datos_T1$Pregunta_12 == "7"] <- 4
datos_T1$Pregunta_12[datos_T1$Pregunta_12 == "8"] <- 2
datos_T1$Pregunta_12[datos_T1$Pregunta_12 == "9"] <- 1

datos_T1$Pregunta_14[datos_T1$Pregunta_14 == "1"] <- 6
datos_T1$Pregunta_14[datos_T1$Pregunta_14 == "2"] <- 7
datos_T1$Pregunta_14[datos_T1$Pregunta_14 == "4"] <- 8
datos_T1$Pregunta_14[datos_T1$Pregunta_14 == "5"] <- 9
datos_T1$Pregunta_14[datos_T1$Pregunta_14 == "6"] <- 5
datos_T1$Pregunta_14[datos_T1$Pregunta_14 == "7"] <- 4
datos_T1$Pregunta_14[datos_T1$Pregunta_14 == "8"] <- 2
datos_T1$Pregunta_14[datos_T1$Pregunta_14 == "9"] <- 1

datos_T1$Pregunta_17[datos_T1$Pregunta_17 == "1"] <- 6
datos_T1$Pregunta_17[datos_T1$Pregunta_17 == "2"] <- 7
datos_T1$Pregunta_17[datos_T1$Pregunta_17 == "4"] <- 8
datos_T1$Pregunta_17[datos_T1$Pregunta_17 == "5"] <- 9
datos_T1$Pregunta_17[datos_T1$Pregunta_17 == "6"] <- 5
datos_T1$Pregunta_17[datos_T1$Pregunta_17 == "7"] <- 4
datos_T1$Pregunta_17[datos_T1$Pregunta_17 == "8"] <- 2
datos_T1$Pregunta_17[datos_T1$Pregunta_17 == "9"] <- 1

datos_T1$Pregunta_21[datos_T1$Pregunta_21 == "1"] <- 6
datos_T1$Pregunta_21[datos_T1$Pregunta_21 == "2"] <- 7
datos_T1$Pregunta_21[datos_T1$Pregunta_21 == "4"] <- 8
datos_T1$Pregunta_21[datos_T1$Pregunta_21 == "5"] <- 9
datos_T1$Pregunta_21[datos_T1$Pregunta_21 == "6"] <- 5
datos_T1$Pregunta_21[datos_T1$Pregunta_21 == "7"] <- 4
datos_T1$Pregunta_21[datos_T1$Pregunta_21 == "8"] <- 2
datos_T1$Pregunta_21[datos_T1$Pregunta_21 == "9"] <- 1

datos_T1$Pregunta_25[datos_T1$Pregunta_25 == "1"] <- 6
datos_T1$Pregunta_25[datos_T1$Pregunta_25 == "2"] <- 7
datos_T1$Pregunta_25[datos_T1$Pregunta_25 == "4"] <- 8
datos_T1$Pregunta_25[datos_T1$Pregunta_25 == "5"] <- 9
datos_T1$Pregunta_25[datos_T1$Pregunta_25 == "6"] <- 5
datos_T1$Pregunta_25[datos_T1$Pregunta_25 == "7"] <- 4
datos_T1$Pregunta_25[datos_T1$Pregunta_25 == "8"] <- 2
datos_T1$Pregunta_25[datos_T1$Pregunta_25 == "9"] <- 1

datos_T1$Pregunta_26[datos_T1$Pregunta_26 == "1"] <- 6
datos_T1$Pregunta_26[datos_T1$Pregunta_26 == "2"] <- 7
datos_T1$Pregunta_26[datos_T1$Pregunta_26 == "4"] <- 8
datos_T1$Pregunta_26[datos_T1$Pregunta_26 == "5"] <- 9
datos_T1$Pregunta_26[datos_T1$Pregunta_26 == "6"] <- 5
datos_T1$Pregunta_26[datos_T1$Pregunta_26 == "7"] <- 4
datos_T1$Pregunta_26[datos_T1$Pregunta_26 == "8"] <- 2
datos_T1$Pregunta_26[datos_T1$Pregunta_26 == "9"] <- 1

datos_T1$Pregunta_28[datos_T1$Pregunta_28 == "1"] <- 6
datos_T1$Pregunta_28[datos_T1$Pregunta_28 == "2"] <- 7
datos_T1$Pregunta_28[datos_T1$Pregunta_28 == "4"] <- 8
datos_T1$Pregunta_28[datos_T1$Pregunta_28 == "5"] <- 9
datos_T1$Pregunta_28[datos_T1$Pregunta_28 == "6"] <- 5
datos_T1$Pregunta_28[datos_T1$Pregunta_28 == "7"] <- 4
datos_T1$Pregunta_28[datos_T1$Pregunta_28 == "8"] <- 2
datos_T1$Pregunta_28[datos_T1$Pregunta_28 == "9"] <- 1

datos_T1$Pregunta_30[datos_T1$Pregunta_30 == "1"] <- 6
datos_T1$Pregunta_30[datos_T1$Pregunta_30 == "2"] <- 7
datos_T1$Pregunta_30[datos_T1$Pregunta_30 == "4"] <- 8
datos_T1$Pregunta_30[datos_T1$Pregunta_30 == "5"] <- 9
datos_T1$Pregunta_30[datos_T1$Pregunta_30 == "6"] <- 5
datos_T1$Pregunta_30[datos_T1$Pregunta_30 == "7"] <- 4
datos_T1$Pregunta_30[datos_T1$Pregunta_30 == "8"] <- 2
datos_T1$Pregunta_30[datos_T1$Pregunta_30 == "9"] <- 1

datos_T1$Pregunta_32[datos_T1$Pregunta_32 == "1"] <- 6
datos_T1$Pregunta_32[datos_T1$Pregunta_32 == "2"] <- 7
datos_T1$Pregunta_32[datos_T1$Pregunta_32 == "4"] <- 8
datos_T1$Pregunta_32[datos_T1$Pregunta_32 == "5"] <- 9
datos_T1$Pregunta_32[datos_T1$Pregunta_32 == "6"] <- 5
datos_T1$Pregunta_32[datos_T1$Pregunta_32 == "7"] <- 4
datos_T1$Pregunta_32[datos_T1$Pregunta_32 == "8"] <- 2
datos_T1$Pregunta_32[datos_T1$Pregunta_32 == "9"] <- 1
```

Convertimos los "0" en NA.

```{r}
datos_T1[datos_T1 == "0"] <- NA
```


```{r}
#Adopcion de perspectivas

AP <- dplyr::select(datos_T1, Pregunta_6, Pregunta_11, Pregunta_15, Pregunta_17, Pregunta_20, Pregunta_26, Pregunta_29, Pregunta_32)

#Comprension emocional

CE <- dplyr::select(datos_T1, Pregunta_1, Pregunta_7, Pregunta_10, Pregunta_13, Pregunta_14, Pregunta_24, Pregunta_27, Pregunta_31, Pregunta_33)

#Estres empatico

EE <- dplyr::select(datos_T1, Pregunta_3, Pregunta_5, Pregunta_8, Pregunta_12, Pregunta_18, Pregunta_23, Pregunta_28, Pregunta_30)

#Alegria empatica

AE <- dplyr::select(datos_T1, Pregunta_2, Pregunta_4, Pregunta_9, Pregunta_16, Pregunta_19, Pregunta_21, Pregunta_22, Pregunta_25)
```



```{r}
#ADOPCION PERSPECTIVAS

#P6 (Falta 1)
AP$Pregunta_6[AP$Pregunta_6 == "2"] <- "1"
AP$Pregunta_6[AP$Pregunta_6 == "3"] <- "2"
AP$Pregunta_6[AP$Pregunta_6 == "4"] <- "3"
AP$Pregunta_6[AP$Pregunta_6 == "5"] <- "4"
```


```{r}
#COMPRENSION EMOCIONAL

#P13 (Falta 1)
CE$Pregunta_13[CE$Pregunta_13 == "2"] <- "1"
CE$Pregunta_13[CE$Pregunta_13 == "3"] <- "2"
CE$Pregunta_13[CE$Pregunta_13 == "4"] <- "3"
CE$Pregunta_13[CE$Pregunta_13 == "5"] <- "4"
```


```{r}
#ALEGRIA EMPATICA

#P2 (Falta 1)
AE$Pregunta_2[AE$Pregunta_2 == "2"] <- "1"
AE$Pregunta_2[AE$Pregunta_2 == "3"] <- "2"
AE$Pregunta_2[AE$Pregunta_2 == "4"] <- "3"
AE$Pregunta_2[AE$Pregunta_2 == "5"] <- "4"

#P4 (Falta 1)
AE$Pregunta_4[AE$Pregunta_4 == "2"] <- "1"
AE$Pregunta_4[AE$Pregunta_4 == "3"] <- "2"
AE$Pregunta_4[AE$Pregunta_4 == "4"] <- "3"
AE$Pregunta_4[AE$Pregunta_4 == "5"] <- "4"

#P9 (Falta 1)
AE$Pregunta_9[AE$Pregunta_9 == "2"] <- "1"
AE$Pregunta_9[AE$Pregunta_9 == "3"] <- "2"
AE$Pregunta_9[AE$Pregunta_9 == "4"] <- "3"
AE$Pregunta_9[AE$Pregunta_9 == "5"] <- "4"
```


Procedemos a aplicar el modelo IRT

```{r}
library(ltm)
```


```{r}
#Adopcion perspectivas

irt_AP <- grm(AP)
summary(irt_AP)
plot(irt_AP)
plot(irt_AP, type="IIC")  
```

```{r}
#Comprension emocional

irt_CE <- grm(CE)
summary(irt_CE)
plot(irt_CE)
plot(irt_CE, type="IIC")
```


```{r}
#Estres empatico

irt_EE <- grm(EE)
summary(irt_EE)
plot(irt_EE)
plot(irt_EE, type="IIC")
```



```{r}
#Alegria empatica

irt_AE <- grm(AE)
summary(irt_AE)
plot(irt_AE)
plot(irt_AE, type = "IIC")
```


