---
title: "Puntuaciones"
author: "Maria Jose Beltran"
date: "5/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Puntuaciones


## T1

```{r include=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(lubridate)
library(plyr)
library(cluster)
library(MASS)
library(readxl)
library(gridExtra)
library(plotly)
library(kableExtra)
library(reshape2)
library(modeest)
```

Importamos los datos. Nos quedamos unicamente con las respuestas a las 33 preguntas de cada alumno (4to curso UIB y Valencia)

```{r}
datosValencia_T1 <- read_excel("/Users/MariaJose/Desktop/TFG/Encuesta/PID_E_II_control3_T1T2T3_4codificado-1.xlsx", sheet = "control3_T1", range = cell_cols("AN:BT")) %>%
  dplyr::rename(Pregunta_1 = "1. Me resulta facil darme cuenta de las intenciones de las personas que me rodean",
                Pregunta_2 = "2. Me siento bien si los demas se divierten (lo pasan bien)",
                Pregunta_3 = "3. No me pongo triste solo porque un amigo lo este",
                Pregunta_4 = "4. Si un amigo consigue un trabajo muy deseado, me entusiasmo con el",
                Pregunta_5 = "5. Me afecta demasiado ver programas de television donde se muestran los problemas de otras personas",
                Pregunta_6 = "6. Antes de tomar una decision, intento tener en cuenta todos los puntos de vista",
                Pregunta_7 = "7. Rara vez reconozco como se siente una persona con solo mirarla",
                Pregunta_8 = "8. Me afecta poco escuchar desgracias sobre personas desconocidas",
                Pregunta_9 = "9. Me hace ilusion  ver que un amigo nuevo se encuentra a gusto en nuestro grupo",
                Pregunta_10 = "10. Me es dificil entender como se siente una persona ante una situacion que no he vivido",
                Pregunta_11 = "11. Cuando un amigo se ha portado mal conmigo, intento entender los motivos por los que lo ha hecho",
                Pregunta_12 = "12. A menos que se trate de algo muy grave, me cuesta llorar con lo que les sucede a otros",
                Pregunta_13 = "13. Reconozco facilmente cuando alguien esta de mal humor",
                Pregunta_14 = "14. No siempre me doy cuenta cuando la persona que tengo al lado se siente mal",
                Pregunta_15 = "15. Intento ponerme en el lugar de los demas para saber como actuaran",
                Pregunta_16 = "16. Cuando a alguien le sucede algo bueno, siento alegria",
                Pregunta_17 = "17. Si tengo una opinion formada no presto mucha atencion a los argumentos de los demas",
                Pregunta_18 = "18. A veces sufro mas con las desgracias de los demas que ellos mismos",
                Pregunta_19 = "19. Me siento feliz solo con ver felices a otras personas",
                Pregunta_20 = "20. Cuando alguien tiene un problema, intento imaginarme como me sentiria si estuviera en su lugar",
                Pregunta_21 = "21. No siento especial alegria si alguien me cuenta que ha tenido un golpe de suerte",
                Pregunta_22 = "22. Cuando veo que alguien  recibe un regalo no puedo reprimir una sonrisa",
                Pregunta_23 = "23. No puedo evitar llorar con los testimonios de personas desconocidas",
                Pregunta_24 = "24. Cuando conozco gente nueva me doy cuenta de la impresion que se han llevado de mi",
                Pregunta_25 = "25. Cuando mis amigos me cuentan que les va bien, no le doy mucha importancia",
                Pregunta_26 = "26. Encuentro dificil ver las cosas desde el punto de vista de otras personas",
                Pregunta_27 = "27. Entender como se siente otra persona es algo muy facil para mi",
                Pregunta_28 = "28. No soy de esas personas que se deprimen con los problemas de los demas",
                Pregunta_29 = "29. Intento comprender mejor a mis amigos mirando las situaciones desde su perspectiva",
                Pregunta_30 = "30. Me considero una persona fria porque no me conmuevo facilmente",
                Pregunta_31 = "31. Me doy cuenta cuando las personas cercanas a mi estan especialmente contentas, aunque no me hayan contado el motivo",
                Pregunta_32 = "32. Me resulta dificil ponerme en el lugar de personas con las que no estoy de acuerdo",
                Pregunta_33 = "33. Me doy cuenta cuando alguien intenta esconder sus verdaderos sentimientos") %>%
  dplyr::mutate(Universidad = "UCV")
```

```{r}
datosUIB_T1 <- read_excel("/Users/MariaJose/Desktop/TFG/Encuesta/PID_E_II_int4_T1T2T3_prog_intensivo_4codificado.xlsx", sheet = "EII_int_T1", range = cell_cols("AN:BT")) %>%
  dplyr::rename(Pregunta_1 = '1TECA1', Pregunta_2 = '1TECA2', Pregunta_3 = '1TECA3',Pregunta_4 = '1TECA4', Pregunta_5 = '1TECA5', Pregunta_6 = '1TECA6', Pregunta_7 = '1TECA7', Pregunta_8 = '1TECA8', Pregunta_9 = '1TECA9', Pregunta_10 = '1TECA10', Pregunta_11 =  '1TECA11', Pregunta_12 = '1TECA12', Pregunta_13 = '1TECA13', Pregunta_14 = '1TECA14', Pregunta_15 = '1TECA15', Pregunta_16 = '1TECA16', Pregunta_17 = '1TECA17',Pregunta_18 = '1TECA18', Pregunta_19 = '1TECA19', Pregunta_20 = '1TECA20', Pregunta_21 = '1TECA21',Pregunta_22 = '1TECA22', Pregunta_23 = '1TECA23',Pregunta_24 = '1TECA24', Pregunta_25 = '1TECA25', Pregunta_26 = '1TECA26', Pregunta_27 = '1TECA27', Pregunta_28 = '1TECA28', Pregunta_29 = '1TECA29', Pregunta_30 = '1TECA30', Pregunta_31 = '1TECA31', Pregunta_32 = '1TECA32', Pregunta_33 = '1TECA33') %>%
  dplyr::mutate(Universidad = "UIB")
```

Juntamos los datos

```{r echo=TRUE, include=FALSE}
datos_T1 <- rbind(datosValencia_T1, datosUIB_T1)
```


Invertimos el orden de las respuestas para las preguntas necesarias

```{r echo=TRUE, include=FALSE}
datos_T1$Pregunta_3[datos_T1$Pregunta_3 == "1"] <- 6
datos_T1$Pregunta_3[datos_T1$Pregunta_3 == "2"] <- 7
datos_T1$Pregunta_3[datos_T1$Pregunta_3 == "4"] <- 8
datos_T1$Pregunta_3[datos_T1$Pregunta_3 == "5"] <- 9
datos_T1$Pregunta_3[datos_T1$Pregunta_3 == "6"] <- 5
datos_T1$Pregunta_3[datos_T1$Pregunta_3 == "7"] <- 4
datos_T1$Pregunta_3[datos_T1$Pregunta_3 == "8"] <- 2
datos_T1$Pregunta_3[datos_T1$Pregunta_3 == "9"] <- 1

datos_T1$Pregunta_7[datos_T1$Pregunta_7 == "1"] <- 6
datos_T1$Pregunta_7[datos_T1$Pregunta_7 == "2"] <- 7
datos_T1$Pregunta_7[datos_T1$Pregunta_7 == "4"] <- 8
datos_T1$Pregunta_7[datos_T1$Pregunta_7 == "5"] <- 9
datos_T1$Pregunta_7[datos_T1$Pregunta_7 == "6"] <- 5
datos_T1$Pregunta_7[datos_T1$Pregunta_7 == "7"] <- 4
datos_T1$Pregunta_7[datos_T1$Pregunta_7 == "8"] <- 2
datos_T1$Pregunta_7[datos_T1$Pregunta_7 == "9"] <- 1

datos_T1$Pregunta_8[datos_T1$Pregunta_8 == "1"] <- 6
datos_T1$Pregunta_8[datos_T1$Pregunta_8 == "2"] <- 7
datos_T1$Pregunta_8[datos_T1$Pregunta_8 == "4"] <- 8
datos_T1$Pregunta_8[datos_T1$Pregunta_8 == "5"] <- 9
datos_T1$Pregunta_8[datos_T1$Pregunta_8 == "6"] <- 5
datos_T1$Pregunta_8[datos_T1$Pregunta_8 == "7"] <- 4
datos_T1$Pregunta_8[datos_T1$Pregunta_8 == "8"] <- 2
datos_T1$Pregunta_8[datos_T1$Pregunta_8 == "9"] <- 1

datos_T1$Pregunta_10[datos_T1$Pregunta_10 == "1"] <- 6
datos_T1$Pregunta_10[datos_T1$Pregunta_10 == "2"] <- 7
datos_T1$Pregunta_10[datos_T1$Pregunta_10 == "4"] <- 8
datos_T1$Pregunta_10[datos_T1$Pregunta_10 == "5"] <- 9
datos_T1$Pregunta_10[datos_T1$Pregunta_10 == "6"] <- 5
datos_T1$Pregunta_10[datos_T1$Pregunta_10 == "7"] <- 4
datos_T1$Pregunta_10[datos_T1$Pregunta_10 == "8"] <- 2
datos_T1$Pregunta_10[datos_T1$Pregunta_10 == "9"] <- 1

datos_T1$Pregunta_12[datos_T1$Pregunta_12 == "1"] <- 6
datos_T1$Pregunta_12[datos_T1$Pregunta_12 == "2"] <- 7
datos_T1$Pregunta_12[datos_T1$Pregunta_12 == "4"] <- 8
datos_T1$Pregunta_12[datos_T1$Pregunta_12 == "5"] <- 9
datos_T1$Pregunta_12[datos_T1$Pregunta_12 == "6"] <- 5
datos_T1$Pregunta_12[datos_T1$Pregunta_12 == "7"] <- 4
datos_T1$Pregunta_12[datos_T1$Pregunta_12 == "8"] <- 2
datos_T1$Pregunta_12[datos_T1$Pregunta_12 == "9"] <- 1

datos_T1$Pregunta_14[datos_T1$Pregunta_14 == "1"] <- 6
datos_T1$Pregunta_14[datos_T1$Pregunta_14 == "2"] <- 7
datos_T1$Pregunta_14[datos_T1$Pregunta_14 == "4"] <- 8
datos_T1$Pregunta_14[datos_T1$Pregunta_14 == "5"] <- 9
datos_T1$Pregunta_14[datos_T1$Pregunta_14 == "6"] <- 5
datos_T1$Pregunta_14[datos_T1$Pregunta_14 == "7"] <- 4
datos_T1$Pregunta_14[datos_T1$Pregunta_14 == "8"] <- 2
datos_T1$Pregunta_14[datos_T1$Pregunta_14 == "9"] <- 1

datos_T1$Pregunta_17[datos_T1$Pregunta_17 == "1"] <- 6
datos_T1$Pregunta_17[datos_T1$Pregunta_17 == "2"] <- 7
datos_T1$Pregunta_17[datos_T1$Pregunta_17 == "4"] <- 8
datos_T1$Pregunta_17[datos_T1$Pregunta_17 == "5"] <- 9
datos_T1$Pregunta_17[datos_T1$Pregunta_17 == "6"] <- 5
datos_T1$Pregunta_17[datos_T1$Pregunta_17 == "7"] <- 4
datos_T1$Pregunta_17[datos_T1$Pregunta_17 == "8"] <- 2
datos_T1$Pregunta_17[datos_T1$Pregunta_17 == "9"] <- 1

datos_T1$Pregunta_21[datos_T1$Pregunta_21 == "1"] <- 6
datos_T1$Pregunta_21[datos_T1$Pregunta_21 == "2"] <- 7
datos_T1$Pregunta_21[datos_T1$Pregunta_21 == "4"] <- 8
datos_T1$Pregunta_21[datos_T1$Pregunta_21 == "5"] <- 9
datos_T1$Pregunta_21[datos_T1$Pregunta_21 == "6"] <- 5
datos_T1$Pregunta_21[datos_T1$Pregunta_21 == "7"] <- 4
datos_T1$Pregunta_21[datos_T1$Pregunta_21 == "8"] <- 2
datos_T1$Pregunta_21[datos_T1$Pregunta_21 == "9"] <- 1

datos_T1$Pregunta_25[datos_T1$Pregunta_25 == "1"] <- 6
datos_T1$Pregunta_25[datos_T1$Pregunta_25 == "2"] <- 7
datos_T1$Pregunta_25[datos_T1$Pregunta_25 == "4"] <- 8
datos_T1$Pregunta_25[datos_T1$Pregunta_25 == "5"] <- 9
datos_T1$Pregunta_25[datos_T1$Pregunta_25 == "6"] <- 5
datos_T1$Pregunta_25[datos_T1$Pregunta_25 == "7"] <- 4
datos_T1$Pregunta_25[datos_T1$Pregunta_25 == "8"] <- 2
datos_T1$Pregunta_25[datos_T1$Pregunta_25 == "9"] <- 1

datos_T1$Pregunta_26[datos_T1$Pregunta_26 == "1"] <- 6
datos_T1$Pregunta_26[datos_T1$Pregunta_26 == "2"] <- 7
datos_T1$Pregunta_26[datos_T1$Pregunta_26 == "4"] <- 8
datos_T1$Pregunta_26[datos_T1$Pregunta_26 == "5"] <- 9
datos_T1$Pregunta_26[datos_T1$Pregunta_26 == "6"] <- 5
datos_T1$Pregunta_26[datos_T1$Pregunta_26 == "7"] <- 4
datos_T1$Pregunta_26[datos_T1$Pregunta_26 == "8"] <- 2
datos_T1$Pregunta_26[datos_T1$Pregunta_26 == "9"] <- 1

datos_T1$Pregunta_28[datos_T1$Pregunta_28 == "1"] <- 6
datos_T1$Pregunta_28[datos_T1$Pregunta_28 == "2"] <- 7
datos_T1$Pregunta_28[datos_T1$Pregunta_28 == "4"] <- 8
datos_T1$Pregunta_28[datos_T1$Pregunta_28 == "5"] <- 9
datos_T1$Pregunta_28[datos_T1$Pregunta_28 == "6"] <- 5
datos_T1$Pregunta_28[datos_T1$Pregunta_28 == "7"] <- 4
datos_T1$Pregunta_28[datos_T1$Pregunta_28 == "8"] <- 2
datos_T1$Pregunta_28[datos_T1$Pregunta_28 == "9"] <- 1

datos_T1$Pregunta_30[datos_T1$Pregunta_30 == "1"] <- 6
datos_T1$Pregunta_30[datos_T1$Pregunta_30 == "2"] <- 7
datos_T1$Pregunta_30[datos_T1$Pregunta_30 == "4"] <- 8
datos_T1$Pregunta_30[datos_T1$Pregunta_30 == "5"] <- 9
datos_T1$Pregunta_30[datos_T1$Pregunta_30 == "6"] <- 5
datos_T1$Pregunta_30[datos_T1$Pregunta_30 == "7"] <- 4
datos_T1$Pregunta_30[datos_T1$Pregunta_30 == "8"] <- 2
datos_T1$Pregunta_30[datos_T1$Pregunta_30 == "9"] <- 1

datos_T1$Pregunta_32[datos_T1$Pregunta_32 == "1"] <- 6
datos_T1$Pregunta_32[datos_T1$Pregunta_32 == "2"] <- 7
datos_T1$Pregunta_32[datos_T1$Pregunta_32 == "4"] <- 8
datos_T1$Pregunta_32[datos_T1$Pregunta_32 == "5"] <- 9
datos_T1$Pregunta_32[datos_T1$Pregunta_32 == "6"] <- 5
datos_T1$Pregunta_32[datos_T1$Pregunta_32 == "7"] <- 4
datos_T1$Pregunta_32[datos_T1$Pregunta_32 == "8"] <- 2
datos_T1$Pregunta_32[datos_T1$Pregunta_32 == "9"] <- 1
```

```{r echo=TRUE}
datos1 <- datos_T1 %>%
  mutate(adopcion_perspectivas = Pregunta_6 + Pregunta_11 + Pregunta_15 + Pregunta_17 + Pregunta_20 + Pregunta_26 + Pregunta_29 + Pregunta_32,
         
         comprension_emocional = Pregunta_1 + Pregunta_7 + Pregunta_10 + Pregunta_13 + Pregunta_14 + Pregunta_24 + Pregunta_27 + Pregunta_31 + Pregunta_33,
         
         estres_empatico = Pregunta_3 + Pregunta_5 + Pregunta_8 + Pregunta_12 + Pregunta_18 + Pregunta_23 + Pregunta_28 + Pregunta_30,
         
         alegria_empatica = Pregunta_2 + Pregunta_4 + Pregunta_9 + Pregunta_16 + Pregunta_19 + Pregunta_21 + Pregunta_22 + Pregunta_25,
         
         score = adopcion_perspectivas + comprension_emocional + estres_empatico + alegria_empatica) %>%
  
  dplyr::select(adopcion_perspectivas, comprension_emocional, estres_empatico, alegria_empatica, score, Universidad)

datos1
```


```{r}
datosT1_UCV <- datos1[datos1$Universidad == "UCV",]
mean(datosT1_UCV$score, na.rm=TRUE)
mfv(datosT1_UCV$score, na_rm=TRUE)
var(datosT1_UCV$score, na.rm=TRUE)
sd(datosT1_UCV$score, na.rm=TRUE)
min(datosT1_UCV$score, na.rm=TRUE)
max(datosT1_UCV$score, na.rm=TRUE)
```

```{r}
datosT1_UIB <- datos1[datos1$Universidad == "UIB",]
mean(datosT1_UIB$score, na.rm=TRUE)
mfv(datosT1_UIB$score, na_rm=TRUE)
var(datosT1_UIB$score, na.rm=TRUE)
sd(datosT1_UIB$score, na.rm=TRUE)
min(datosT1_UIB$score, na.rm=TRUE)
max(datosT1_UIB$score, na.rm=TRUE)
```

## T2

```{r}
datosValencia_T2 <- read_excel("/Users/MariaJose/Desktop/TFG/Encuesta/PID_E_II_control3_T1T2T3_4codificado-1.xlsx", sheet = "control3_T2", range = cell_cols("AN:BT")) %>%
  dplyr::rename(Pregunta_1 = "1. Me resulta fácil darme cuenta de las intenciones de las personas que me rodean",
                Pregunta_2 = "2. Me siento bien si los/as demás se divierten (lo pasan bien)",
                Pregunta_3 = "3. No me pongo triste sólo porque un amigo lo esté.",
                Pregunta_4 = "4. Si un/a amigo/a consigue un trabajo muy deseado, me entusiasmo con él.",
                Pregunta_5 = "5. Me afecta demasiado ver programas de televisión donde se muestran los problemas de otras personas.",
                Pregunta_6 = "6. Antes de tomar una decisión, intento tener en cuenta todos los puntos de vista.",
                Pregunta_7 = "7. Rara vez reconozco cómo se siente una persona con sólo mirarla",
                Pregunta_8 = "8. Me afecta poco escuchar desgracias sobre personas desconocidas.",
                Pregunta_9 = "9. Me hace ilusión  ver que un/a amigo/a nuevo/a se encuentra a gusto en nuestro grupo",
                Pregunta_10 = "10. Me es difícil entender cómo se siente una persona ante una situación que no he vivido.",
                Pregunta_11 = "11. Cuando un/a amigo/a se ha portado mal conmigo, intento entender los motivos por los que lo ha hecho",
                Pregunta_12 = "12. A menos que se trate de algo muy grave, me cuesta llorar con lo que les sucede a otros/as",
                Pregunta_13 = "13. Reconozco fácilmente cuándo alguien está de mal humor",
                Pregunta_14 = "14. No siempre me doy cuenta cuando la persona que tengo al lado se siente mal",
                Pregunta_15 = "15. Intento ponerme en el lugar de los demás para saber cómo actuarán.",
                Pregunta_16 = "16. Cuando a alguien le sucede algo bueno, siento alegría",
                Pregunta_17 = "17. Si tengo una opinión formada no presto mucha atención a los argumentos de los demás.",
                Pregunta_18 = "18. A veces sufro más con las desgracias de los demás que ellos mismos.",
                Pregunta_19 = "19. Me siento feliz sólo con ver felices a otras personas",
                Pregunta_20 = "20. Cuando alguien tiene un problema, intento imaginarme cómo me sentiría si estuviera en su lugar.",
                Pregunta_21 = "21. No siento especial alegría si alguien me cuenta que ha tenido un golpe de suerte",
                Pregunta_22 = "22. Cuando veo que alguien  recibe un regalo no puedo reprimir una sonrisa.",
                Pregunta_23 = "23. No puedo evitar llorar con los testimonios de personas desconocidas.",
                Pregunta_24 = "24. Cuando conozco gente nueva me doy cuenta de la impresión que se han llevado de mí.",
                Pregunta_25 = "25. Cuando mis amigos me cuentan que les va bien, no le doy mucha importancia.",
                Pregunta_26 = "26. Encuentro difícil ver las cosas desde el punto de vista de otras personas.",
                Pregunta_27 = "27. Entender cómo se siente otra persona es algo muy fácil para mí",
                Pregunta_28 = "28. No soy de esas personas que se deprimen con los problemas de los demás.",
                Pregunta_29 = "29. Intento comprender mejor a mis amigos/as mirando las situaciones desde su perspectiva.",
                Pregunta_30 = "30. Me considero una persona fría porque no me conmuevo fácilmente.",
                Pregunta_31 = "31. Me doy cuenta cuando las personas cercanas a mí están especialmente contentas, aunque no me hayan contado el motivo",
                Pregunta_32 = "32. Me resulta difícil ponerme en el lugar de personas con las que no estoy de acuerdo.",
                Pregunta_33 = "33. Me doy cuenta cuando alguien intenta esconder sus verdaderos sentimientos.") %>%
  dplyr::mutate(Universidad = "UCV")
```

```{r}
datosUIB_T2 <- read_excel("/Users/MariaJose/Desktop/TFG/Encuesta/PID_E_II_int4_T1T2T3_prog_intensivo_4codificado.xlsx", sheet = "EII_int_T2", range = cell_cols("AN:BT")) %>%
  dplyr::rename(Pregunta_1 = '2TECA1', Pregunta_2 = '2TECA2', Pregunta_3 = '2TECA3',Pregunta_4 = '2TECA4', Pregunta_5 = '2TECA5', Pregunta_6 = '2TECA6', Pregunta_7 = '2TECA7', Pregunta_8 = '2TECA8', Pregunta_9 = '2TECA9', Pregunta_10 = '2TECA10', Pregunta_11 =  '2TECA11', Pregunta_12 = '2TECA12', Pregunta_13 = '2TECA13', Pregunta_14 = '2TECA14', Pregunta_15 = '2TECA15', Pregunta_16 = '2TECA16', Pregunta_17 = '2TECA17',Pregunta_18 = '2TECA18', Pregunta_19 = '2TECA19', Pregunta_20 = '2TECA20', Pregunta_21 = '2TECA21',Pregunta_22 = '2TECA22', Pregunta_23 = '2TECA23',Pregunta_24 = '2TECA24', Pregunta_25 = '2TECA25', Pregunta_26 = '2TECA26', Pregunta_27 = '2TECA27', Pregunta_28 = '2TECA28', Pregunta_29 = '2TECA29', Pregunta_30 = '2TECA30', Pregunta_31 = '2TECA31', Pregunta_32 = '2TECA32', Pregunta_33 = '2TECA33') %>%
  dplyr::mutate(Universidad = "UIB")
```

Juntamos los datos

```{r echo=TRUE, include=FALSE}
datos_T2 <- rbind(datosValencia_T2, datosUIB_T2)
```

```{r echo=TRUE}
datos_T2$Pregunta_3[datos_T2$Pregunta_3 == "1"] <- 6
datos_T2$Pregunta_3[datos_T2$Pregunta_3 == "2"] <- 7
datos_T2$Pregunta_3[datos_T2$Pregunta_3 == "4"] <- 8
datos_T2$Pregunta_3[datos_T2$Pregunta_3 == "5"] <- 9
datos_T2$Pregunta_3[datos_T2$Pregunta_3 == "6"] <- 5
datos_T2$Pregunta_3[datos_T2$Pregunta_3 == "7"] <- 4
datos_T2$Pregunta_3[datos_T2$Pregunta_3 == "8"] <- 2
datos_T2$Pregunta_3[datos_T2$Pregunta_3 == "9"] <- 1

datos_T2$Pregunta_7[datos_T2$Pregunta_7 == "1"] <- 6
datos_T2$Pregunta_7[datos_T2$Pregunta_7 == "2"] <- 7
datos_T2$Pregunta_7[datos_T2$Pregunta_7 == "4"] <- 8
datos_T2$Pregunta_7[datos_T2$Pregunta_7 == "5"] <- 9
datos_T2$Pregunta_7[datos_T2$Pregunta_7 == "6"] <- 5
datos_T2$Pregunta_7[datos_T2$Pregunta_7 == "7"] <- 4
datos_T2$Pregunta_7[datos_T2$Pregunta_7 == "8"] <- 2
datos_T2$Pregunta_7[datos_T2$Pregunta_7 == "9"] <- 1

datos_T2$Pregunta_8[datos_T2$Pregunta_8 == "1"] <- 6
datos_T2$Pregunta_8[datos_T2$Pregunta_8 == "2"] <- 7
datos_T2$Pregunta_8[datos_T2$Pregunta_8 == "4"] <- 8
datos_T2$Pregunta_8[datos_T2$Pregunta_8 == "5"] <- 9
datos_T2$Pregunta_8[datos_T2$Pregunta_8 == "6"] <- 5
datos_T2$Pregunta_8[datos_T2$Pregunta_8 == "7"] <- 4
datos_T2$Pregunta_8[datos_T2$Pregunta_8 == "8"] <- 2
datos_T2$Pregunta_8[datos_T2$Pregunta_8 == "9"] <- 1

datos_T2$Pregunta_10[datos_T2$Pregunta_10 == "1"] <- 6
datos_T2$Pregunta_10[datos_T2$Pregunta_10 == "2"] <- 7
datos_T2$Pregunta_10[datos_T2$Pregunta_10 == "4"] <- 8
datos_T2$Pregunta_10[datos_T2$Pregunta_10 == "5"] <- 9
datos_T2$Pregunta_10[datos_T2$Pregunta_10 == "6"] <- 5
datos_T2$Pregunta_10[datos_T2$Pregunta_10 == "7"] <- 4
datos_T2$Pregunta_10[datos_T2$Pregunta_10 == "8"] <- 2
datos_T2$Pregunta_10[datos_T2$Pregunta_10 == "9"] <- 1

datos_T2$Pregunta_12[datos_T2$Pregunta_12 == "1"] <- 6
datos_T2$Pregunta_12[datos_T2$Pregunta_12 == "2"] <- 7
datos_T2$Pregunta_12[datos_T2$Pregunta_12 == "4"] <- 8
datos_T2$Pregunta_12[datos_T2$Pregunta_12 == "5"] <- 9
datos_T2$Pregunta_12[datos_T2$Pregunta_12 == "6"] <- 5
datos_T2$Pregunta_12[datos_T2$Pregunta_12 == "7"] <- 4
datos_T2$Pregunta_12[datos_T2$Pregunta_12 == "8"] <- 2
datos_T2$Pregunta_12[datos_T2$Pregunta_12 == "9"] <- 1

datos_T2$Pregunta_14[datos_T2$Pregunta_14 == "1"] <- 6
datos_T2$Pregunta_14[datos_T2$Pregunta_14 == "2"] <- 7
datos_T2$Pregunta_14[datos_T2$Pregunta_14 == "4"] <- 8
datos_T2$Pregunta_14[datos_T2$Pregunta_14 == "5"] <- 9
datos_T2$Pregunta_14[datos_T2$Pregunta_14 == "6"] <- 5
datos_T2$Pregunta_14[datos_T2$Pregunta_14 == "7"] <- 4
datos_T2$Pregunta_14[datos_T2$Pregunta_14 == "8"] <- 2
datos_T2$Pregunta_14[datos_T2$Pregunta_14 == "9"] <- 1

datos_T2$Pregunta_17[datos_T2$Pregunta_17 == "1"] <- 6
datos_T2$Pregunta_17[datos_T2$Pregunta_17 == "2"] <- 7
datos_T2$Pregunta_17[datos_T2$Pregunta_17 == "4"] <- 8
datos_T2$Pregunta_17[datos_T2$Pregunta_17 == "5"] <- 9
datos_T2$Pregunta_17[datos_T2$Pregunta_17 == "6"] <- 5
datos_T2$Pregunta_17[datos_T2$Pregunta_17 == "7"] <- 4
datos_T2$Pregunta_17[datos_T2$Pregunta_17 == "8"] <- 2
datos_T2$Pregunta_17[datos_T2$Pregunta_17 == "9"] <- 1

datos_T2$Pregunta_21[datos_T2$Pregunta_21 == "1"] <- 6
datos_T2$Pregunta_21[datos_T2$Pregunta_21 == "2"] <- 7
datos_T2$Pregunta_21[datos_T2$Pregunta_21 == "4"] <- 8
datos_T2$Pregunta_21[datos_T2$Pregunta_21 == "5"] <- 9
datos_T2$Pregunta_21[datos_T2$Pregunta_21 == "6"] <- 5
datos_T2$Pregunta_21[datos_T2$Pregunta_21 == "7"] <- 4
datos_T2$Pregunta_21[datos_T2$Pregunta_21 == "8"] <- 2
datos_T2$Pregunta_21[datos_T2$Pregunta_21 == "9"] <- 1

datos_T2$Pregunta_25[datos_T2$Pregunta_25 == "1"] <- 6
datos_T2$Pregunta_25[datos_T2$Pregunta_25 == "2"] <- 7
datos_T2$Pregunta_25[datos_T2$Pregunta_25 == "4"] <- 8
datos_T2$Pregunta_25[datos_T2$Pregunta_25 == "5"] <- 9
datos_T2$Pregunta_25[datos_T2$Pregunta_25 == "6"] <- 5
datos_T2$Pregunta_25[datos_T2$Pregunta_25 == "7"] <- 4
datos_T2$Pregunta_25[datos_T2$Pregunta_25 == "8"] <- 2
datos_T2$Pregunta_25[datos_T2$Pregunta_25 == "9"] <- 1

datos_T2$Pregunta_26[datos_T2$Pregunta_26 == "1"] <- 6
datos_T2$Pregunta_26[datos_T2$Pregunta_26 == "2"] <- 7
datos_T2$Pregunta_26[datos_T2$Pregunta_26 == "4"] <- 8
datos_T2$Pregunta_26[datos_T2$Pregunta_26 == "5"] <- 9
datos_T2$Pregunta_26[datos_T2$Pregunta_26 == "6"] <- 5
datos_T2$Pregunta_26[datos_T2$Pregunta_26 == "7"] <- 4
datos_T2$Pregunta_26[datos_T2$Pregunta_26 == "8"] <- 2
datos_T2$Pregunta_26[datos_T2$Pregunta_26 == "9"] <- 1

datos_T2$Pregunta_28[datos_T2$Pregunta_28 == "1"] <- 6
datos_T2$Pregunta_28[datos_T2$Pregunta_28 == "2"] <- 7
datos_T2$Pregunta_28[datos_T2$Pregunta_28 == "4"] <- 8
datos_T2$Pregunta_28[datos_T2$Pregunta_28 == "5"] <- 9
datos_T2$Pregunta_28[datos_T2$Pregunta_28 == "6"] <- 5
datos_T2$Pregunta_28[datos_T2$Pregunta_28 == "7"] <- 4
datos_T2$Pregunta_28[datos_T2$Pregunta_28 == "8"] <- 2
datos_T2$Pregunta_28[datos_T2$Pregunta_28 == "9"] <- 1

datos_T2$Pregunta_30[datos_T2$Pregunta_30 == "1"] <- 6
datos_T2$Pregunta_30[datos_T2$Pregunta_30 == "2"] <- 7
datos_T2$Pregunta_30[datos_T2$Pregunta_30 == "4"] <- 8
datos_T2$Pregunta_30[datos_T2$Pregunta_30 == "5"] <- 9
datos_T2$Pregunta_30[datos_T2$Pregunta_30 == "6"] <- 5
datos_T2$Pregunta_30[datos_T2$Pregunta_30 == "7"] <- 4
datos_T2$Pregunta_30[datos_T2$Pregunta_30 == "8"] <- 2
datos_T2$Pregunta_30[datos_T2$Pregunta_30 == "9"] <- 1

datos_T2$Pregunta_32[datos_T2$Pregunta_32 == "1"] <- 6
datos_T2$Pregunta_32[datos_T2$Pregunta_32 == "2"] <- 7
datos_T2$Pregunta_32[datos_T2$Pregunta_32 == "4"] <- 8
datos_T2$Pregunta_32[datos_T2$Pregunta_32 == "5"] <- 9
datos_T2$Pregunta_32[datos_T2$Pregunta_32 == "6"] <- 5
datos_T2$Pregunta_32[datos_T2$Pregunta_32 == "7"] <- 4
datos_T2$Pregunta_32[datos_T2$Pregunta_32 == "8"] <- 2
datos_T2$Pregunta_32[datos_T2$Pregunta_32 == "9"] <- 1
```

```{r echo=TRUE}
datos2 <- datos_T2 %>%
  mutate(adopcion_perspectivas = Pregunta_6 + Pregunta_11 + Pregunta_15 + Pregunta_17 + Pregunta_20 + Pregunta_26 + Pregunta_29 + Pregunta_32,
         
         comprension_emocional = Pregunta_1 + Pregunta_7 + Pregunta_10 + Pregunta_13 + Pregunta_14 + Pregunta_24 + Pregunta_27 + Pregunta_31 + Pregunta_33,
         
         estres_empatico = Pregunta_3 + Pregunta_5 + Pregunta_8 + Pregunta_12 + Pregunta_18 + Pregunta_23 + Pregunta_28 + Pregunta_30,
         
         alegria_empatica = Pregunta_2 + Pregunta_4 + Pregunta_9 + Pregunta_16 + Pregunta_19 + Pregunta_21 + Pregunta_22 + Pregunta_25,
         
         score = adopcion_perspectivas + comprension_emocional + estres_empatico + alegria_empatica) %>%
  
  dplyr::select(adopcion_perspectivas, comprension_emocional, estres_empatico, alegria_empatica, score, Universidad)

datos2
```

```{r}
datosT2_UCV <- datos2[datos2$Universidad == "UCV",]
mean(datosT2_UCV$score, na.rm=TRUE)
mfv(datosT2_UCV$score, na_rm=TRUE)
var(datosT2_UCV$score, na.rm=TRUE)
sd(datosT2_UCV$score, na.rm=TRUE)
min(datosT2_UCV$score, na.rm=TRUE)
max(datosT2_UCV$score, na.rm=TRUE)
```

```{r}
datosT2_UIB <- datos2[datos2$Universidad == "UIB",]
mean(datosT2_UIB$score, na.rm=TRUE)
mfv(datosT2_UIB$score, na_rm=TRUE)
var(datosT2_UIB$score, na.rm=TRUE)
sd(datosT2_UIB$score, na.rm=TRUE)
min(datosT2_UIB$score, na.rm=TRUE)
max(datosT2_UIB$score, na.rm=TRUE)
```


## T3

```{r}
datosValencia_T3 <- read_excel("/Users/MariaJose/Desktop/TFG/Encuesta/PID_E_II_control3_T1T2T3_4codificado-1.xlsx", sheet = "control3_T3", range = cell_cols("AN:BT")) %>%
  dplyr::rename(Pregunta_1 = "1. Me resulta fácil darme cuenta de las intenciones de las personas que me rodean",
                Pregunta_2 = "2. Me siento bien si los/as demás se divierten (lo pasan bien)",
                Pregunta_3 = "3. No me pongo triste sólo porque un amigo lo esté.",
                Pregunta_4 = "4. Si un/a amigo/a consigue un trabajo muy deseado, me entusiasmo con él.",
                Pregunta_5 = "5. Me afecta demasiado ver programas de televisión donde se muestran los problemas de otras personas.",
                Pregunta_6 = "6. Antes de tomar una decisión, intento tener en cuenta todos los puntos de vista.",
                Pregunta_7 = "7. Rara vez reconozco cómo se siente una persona con sólo mirarla",
                Pregunta_8 = "8. Me afecta poco escuchar desgracias sobre personas desconocidas.",
                Pregunta_9 = "9. Me hace ilusión  ver que un/a amigo/a nuevo/a se encuentra a gusto en nuestro grupo",
                Pregunta_10 = "10. Me es difícil entender cómo se siente una persona ante una situación que no he vivido.",
                Pregunta_11 = "11. Cuando un/a amigo/a se ha portado mal conmigo, intento entender los motivos por los que lo ha hecho",
                Pregunta_12 = "12. A menos que se trate de algo muy grave, me cuesta llorar con lo que les sucede a otros/as",
                Pregunta_13 = "13. Reconozco fácilmente cuándo alguien está de mal humor",
                Pregunta_14 = "14. No siempre me doy cuenta cuando la persona que tengo al lado se siente mal",
                Pregunta_15 = "15. Intento ponerme en el lugar de los demás para saber cómo actuarán.",
                Pregunta_16 = "16. Cuando a alguien le sucede algo bueno, siento alegría",
                Pregunta_17 = "17. Si tengo una opinión formada no presto mucha atención a los argumentos de los demás.",
                Pregunta_18 = "18. A veces sufro más con las desgracias de los demás que ellos mismos.",
                Pregunta_19 = "19. Me siento feliz sólo con ver felices a otras personas",
                Pregunta_20 = "20. Cuando alguien tiene un problema, intento imaginarme cómo me sentiría si estuviera en su lugar.",
                Pregunta_21 = "21. No siento especial alegría si alguien me cuenta que ha tenido un golpe de suerte",
                Pregunta_22 = "22. Cuando veo que alguien  recibe un regalo no puedo reprimir una sonrisa.",
                Pregunta_23 = "23. No puedo evitar llorar con los testimonios de personas desconocidas.",
                Pregunta_24 = "24. Cuando conozco gente nueva me doy cuenta de la impresión que se han llevado de mí.",
                Pregunta_25 = "25. Cuando mis amigos me cuentan que les va bien, no le doy mucha importancia.",
                Pregunta_26 = "26. Encuentro difícil ver las cosas desde el punto de vista de otras personas.",
                Pregunta_27 = "27. Entender cómo se siente otra persona es algo muy fácil para mí",
                Pregunta_28 = "28. No soy de esas personas que se deprimen con los problemas de los demás.",
                Pregunta_29 = "29. Intento comprender mejor a mis amigos/as mirando las situaciones desde su perspectiva.",
                Pregunta_30 = "30. Me considero una persona fría porque no me conmuevo fácilmente.",
                Pregunta_31 = "31. Me doy cuenta cuando las personas cercanas a mí están especialmente contentas, aunque no me hayan contado el motivo",
                Pregunta_32 = "32. Me resulta difícil ponerme en el lugar de personas con las que no estoy de acuerdo.",
                Pregunta_33 = "33. Me doy cuenta cuando alguien intenta esconder sus verdaderos sentimientos.") %>%
  dplyr::mutate(Universidad = "UCV")
```

```{r}
datosUIB_T3 <- read_excel("/Users/MariaJose/Desktop/TFG/Encuesta/PID_E_II_int4_T1T2T3_prog_intensivo_4codificado.xlsx", sheet = "EII_int_T3", range = cell_cols("AN:BT")) %>%
  dplyr::rename(Pregunta_1 = '3TECA1', Pregunta_2 = '3TECA2', Pregunta_3 = '3TECA3', Pregunta_4 = '3TECA4', Pregunta_5 = '3TECA5', Pregunta_6 = '3TECA6', Pregunta_7 = '3TECA7', Pregunta_8 = '3TECA8', Pregunta_9 = '3TECA9', Pregunta_10 = '3TECA10', Pregunta_11 =  '3TECA11', Pregunta_12 = '3TECA12', Pregunta_13 = '3TECA13', Pregunta_14 = '3TECA14', Pregunta_15 = '3TECA15', Pregunta_16 = '3TECA16', Pregunta_17 = '3TECA17',Pregunta_18 = '3TECA18', Pregunta_19 = '3TECA19', Pregunta_20 = '3TECA20', Pregunta_21 = '3TECA21',Pregunta_22 = '3TECA22', Pregunta_23 = '3TECA23',Pregunta_24 = '3TECA24', Pregunta_25 = '3TECA25', Pregunta_26 = '3TECA26', Pregunta_27 = '3TECA27', Pregunta_28 = '3TECA28', Pregunta_29 = '3TECA29', Pregunta_30 = '3TECA30', Pregunta_31 = '3TECA31', Pregunta_32 = '3TECA32', Pregunta_33 = '3TECA 33') %>%
  dplyr::mutate(Universidad = "UIB")
```

Juntamos los datos

```{r echo=TRUE, include=FALSE}
datos_T3 <- rbind(datosValencia_T3, datosUIB_T3)
```

```{r echo=TRUE}
datos_T3$Pregunta_3[datos_T3$Pregunta_3 == "1"] <- 6
datos_T3$Pregunta_3[datos_T3$Pregunta_3 == "2"] <- 7
datos_T3$Pregunta_3[datos_T3$Pregunta_3 == "4"] <- 8
datos_T3$Pregunta_3[datos_T3$Pregunta_3 == "5"] <- 9
datos_T3$Pregunta_3[datos_T3$Pregunta_3 == "6"] <- 5
datos_T3$Pregunta_3[datos_T3$Pregunta_3 == "7"] <- 4
datos_T3$Pregunta_3[datos_T3$Pregunta_3 == "8"] <- 2
datos_T3$Pregunta_3[datos_T3$Pregunta_3 == "9"] <- 1

datos_T3$Pregunta_7[datos_T3$Pregunta_7 == "1"] <- 6
datos_T3$Pregunta_7[datos_T3$Pregunta_7 == "2"] <- 7
datos_T3$Pregunta_7[datos_T3$Pregunta_7 == "4"] <- 8
datos_T3$Pregunta_7[datos_T3$Pregunta_7 == "5"] <- 9
datos_T3$Pregunta_7[datos_T3$Pregunta_7 == "6"] <- 5
datos_T3$Pregunta_7[datos_T3$Pregunta_7 == "7"] <- 4
datos_T3$Pregunta_7[datos_T3$Pregunta_7 == "8"] <- 2
datos_T3$Pregunta_7[datos_T3$Pregunta_7 == "9"] <- 1

datos_T3$Pregunta_8[datos_T3$Pregunta_8 == "1"] <- 6
datos_T3$Pregunta_8[datos_T3$Pregunta_8 == "2"] <- 7
datos_T3$Pregunta_8[datos_T3$Pregunta_8 == "4"] <- 8
datos_T3$Pregunta_8[datos_T3$Pregunta_8 == "5"] <- 9
datos_T3$Pregunta_8[datos_T3$Pregunta_8 == "6"] <- 5
datos_T3$Pregunta_8[datos_T3$Pregunta_8 == "7"] <- 4
datos_T3$Pregunta_8[datos_T3$Pregunta_8 == "8"] <- 2
datos_T3$Pregunta_8[datos_T3$Pregunta_8 == "9"] <- 1

datos_T3$Pregunta_10[datos_T3$Pregunta_10 == "1"] <- 6
datos_T3$Pregunta_10[datos_T3$Pregunta_10 == "2"] <- 7
datos_T3$Pregunta_10[datos_T3$Pregunta_10 == "4"] <- 8
datos_T3$Pregunta_10[datos_T3$Pregunta_10 == "5"] <- 9
datos_T3$Pregunta_10[datos_T3$Pregunta_10 == "6"] <- 5
datos_T3$Pregunta_10[datos_T3$Pregunta_10 == "7"] <- 4
datos_T3$Pregunta_10[datos_T3$Pregunta_10 == "8"] <- 2
datos_T3$Pregunta_10[datos_T3$Pregunta_10 == "9"] <- 1

datos_T3$Pregunta_12[datos_T3$Pregunta_12 == "1"] <- 6
datos_T3$Pregunta_12[datos_T3$Pregunta_12 == "2"] <- 7
datos_T3$Pregunta_12[datos_T3$Pregunta_12 == "4"] <- 8
datos_T3$Pregunta_12[datos_T3$Pregunta_12 == "5"] <- 9
datos_T3$Pregunta_12[datos_T3$Pregunta_12 == "6"] <- 5
datos_T3$Pregunta_12[datos_T3$Pregunta_12 == "7"] <- 4
datos_T3$Pregunta_12[datos_T3$Pregunta_12 == "8"] <- 2
datos_T3$Pregunta_12[datos_T3$Pregunta_12 == "9"] <- 1

datos_T3$Pregunta_14[datos_T3$Pregunta_14 == "1"] <- 6
datos_T3$Pregunta_14[datos_T3$Pregunta_14 == "2"] <- 7
datos_T3$Pregunta_14[datos_T3$Pregunta_14 == "4"] <- 8
datos_T3$Pregunta_14[datos_T3$Pregunta_14 == "5"] <- 9
datos_T3$Pregunta_14[datos_T3$Pregunta_14 == "6"] <- 5
datos_T3$Pregunta_14[datos_T3$Pregunta_14 == "7"] <- 4
datos_T3$Pregunta_14[datos_T3$Pregunta_14 == "8"] <- 2
datos_T3$Pregunta_14[datos_T3$Pregunta_14 == "9"] <- 1

datos_T3$Pregunta_17[datos_T3$Pregunta_17 == "1"] <- 6
datos_T3$Pregunta_17[datos_T3$Pregunta_17 == "2"] <- 7
datos_T3$Pregunta_17[datos_T3$Pregunta_17 == "4"] <- 8
datos_T3$Pregunta_17[datos_T3$Pregunta_17 == "5"] <- 9
datos_T3$Pregunta_17[datos_T3$Pregunta_17 == "6"] <- 5
datos_T3$Pregunta_17[datos_T3$Pregunta_17 == "7"] <- 4
datos_T3$Pregunta_17[datos_T3$Pregunta_17 == "8"] <- 2
datos_T3$Pregunta_17[datos_T3$Pregunta_17 == "9"] <- 1

datos_T3$Pregunta_21[datos_T3$Pregunta_21 == "1"] <- 6
datos_T3$Pregunta_21[datos_T3$Pregunta_21 == "2"] <- 7
datos_T3$Pregunta_21[datos_T3$Pregunta_21 == "4"] <- 8
datos_T3$Pregunta_21[datos_T3$Pregunta_21 == "5"] <- 9
datos_T3$Pregunta_21[datos_T3$Pregunta_21 == "6"] <- 5
datos_T3$Pregunta_21[datos_T3$Pregunta_21 == "7"] <- 4
datos_T3$Pregunta_21[datos_T3$Pregunta_21 == "8"] <- 2
datos_T3$Pregunta_21[datos_T3$Pregunta_21 == "9"] <- 1

datos_T3$Pregunta_25[datos_T3$Pregunta_25 == "1"] <- 6
datos_T3$Pregunta_25[datos_T3$Pregunta_25 == "2"] <- 7
datos_T3$Pregunta_25[datos_T3$Pregunta_25 == "4"] <- 8
datos_T3$Pregunta_25[datos_T3$Pregunta_25 == "5"] <- 9
datos_T3$Pregunta_25[datos_T3$Pregunta_25 == "6"] <- 5
datos_T3$Pregunta_25[datos_T3$Pregunta_25 == "7"] <- 4
datos_T3$Pregunta_25[datos_T3$Pregunta_25 == "8"] <- 2
datos_T3$Pregunta_25[datos_T3$Pregunta_25 == "9"] <- 1

datos_T3$Pregunta_26[datos_T3$Pregunta_26 == "1"] <- 6
datos_T3$Pregunta_26[datos_T3$Pregunta_26 == "2"] <- 7
datos_T3$Pregunta_26[datos_T3$Pregunta_26 == "4"] <- 8
datos_T3$Pregunta_26[datos_T3$Pregunta_26 == "5"] <- 9
datos_T3$Pregunta_26[datos_T3$Pregunta_26 == "6"] <- 5
datos_T3$Pregunta_26[datos_T3$Pregunta_26 == "7"] <- 4
datos_T3$Pregunta_26[datos_T3$Pregunta_26 == "8"] <- 2
datos_T3$Pregunta_26[datos_T3$Pregunta_26 == "9"] <- 1

datos_T3$Pregunta_28[datos_T3$Pregunta_28 == "1"] <- 6
datos_T3$Pregunta_28[datos_T3$Pregunta_28 == "2"] <- 7
datos_T3$Pregunta_28[datos_T3$Pregunta_28 == "4"] <- 8
datos_T3$Pregunta_28[datos_T3$Pregunta_28 == "5"] <- 9
datos_T3$Pregunta_28[datos_T3$Pregunta_28 == "6"] <- 5
datos_T3$Pregunta_28[datos_T3$Pregunta_28 == "7"] <- 4
datos_T3$Pregunta_28[datos_T3$Pregunta_28 == "8"] <- 2
datos_T3$Pregunta_28[datos_T3$Pregunta_28 == "9"] <- 1

datos_T3$Pregunta_30[datos_T3$Pregunta_30 == "1"] <- 6
datos_T3$Pregunta_30[datos_T3$Pregunta_30 == "2"] <- 7
datos_T3$Pregunta_30[datos_T3$Pregunta_30 == "4"] <- 8
datos_T3$Pregunta_30[datos_T3$Pregunta_30 == "5"] <- 9
datos_T3$Pregunta_30[datos_T3$Pregunta_30 == "6"] <- 5
datos_T3$Pregunta_30[datos_T3$Pregunta_30 == "7"] <- 4
datos_T3$Pregunta_30[datos_T3$Pregunta_30 == "8"] <- 2
datos_T3$Pregunta_30[datos_T3$Pregunta_30 == "9"] <- 1

datos_T3$Pregunta_32[datos_T3$Pregunta_32 == "1"] <- 6
datos_T3$Pregunta_32[datos_T3$Pregunta_32 == "2"] <- 7
datos_T3$Pregunta_32[datos_T3$Pregunta_32 == "4"] <- 8
datos_T3$Pregunta_32[datos_T3$Pregunta_32 == "5"] <- 9
datos_T3$Pregunta_32[datos_T3$Pregunta_32 == "6"] <- 5
datos_T3$Pregunta_32[datos_T3$Pregunta_32 == "7"] <- 4
datos_T3$Pregunta_32[datos_T3$Pregunta_32 == "8"] <- 2
datos_T3$Pregunta_32[datos_T3$Pregunta_32 == "9"] <- 1
```

```{r echo=TRUE}
datos3 <- datos_T3 %>%
  mutate(adopcion_perspectivas = Pregunta_6 + Pregunta_11 + Pregunta_15 + Pregunta_17 + Pregunta_20 + Pregunta_26 + Pregunta_29 + Pregunta_32,
         
         comprension_emocional = Pregunta_1 + Pregunta_7 + Pregunta_10 + Pregunta_13 + Pregunta_14 + Pregunta_24 + Pregunta_27 + Pregunta_31 + Pregunta_33,
         
         estres_empatico = Pregunta_3 + Pregunta_5 + Pregunta_8 + Pregunta_12 + Pregunta_18 + Pregunta_23 + Pregunta_28 + Pregunta_30,
         
         alegria_empatica = Pregunta_2 + Pregunta_4 + Pregunta_9 + Pregunta_16 + Pregunta_19 + Pregunta_21 + Pregunta_22 + Pregunta_25,
         
         score = adopcion_perspectivas + comprension_emocional + estres_empatico + alegria_empatica) %>%
  
  dplyr::select(adopcion_perspectivas, comprension_emocional, estres_empatico, alegria_empatica, score, Universidad)

datos3
```

```{r}
datosT3_UCV <- datos3[datos3$Universidad == "UCV",]
mean(datosT3_UCV$score, na.rm=TRUE)
mfv(datosT3_UCV$score, na_rm=TRUE)
var(datosT3_UCV$score, na.rm=TRUE)
sd(datosT3_UCV$score, na.rm=TRUE)
min(datosT3_UCV$score, na.rm=TRUE)
max(datosT3_UCV$score, na.rm=TRUE)
```

```{r}
datosT3_UIB <- datos3[datos3$Universidad == "UIB",]
mean(datosT3_UIB$score, na.rm=TRUE)
mfv(datosT3_UIB$score, na_rm = TRUE)
var(datosT3_UIB$score, na.rm=TRUE)
sd(datosT3_UIB$score, na.rm=TRUE)
min(datosT3_UIB$score, na.rm=TRUE)
max(datosT3_UIB$score, na.rm=TRUE)
```
